[build]
# Redirects the 'target' directory to a local, non-synced folder
target-dir = "C:/temp/rust-builds/md"
rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
